/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaxIndexRouteImport } from './routes/tax.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AccountingIndexRouteImport } from './routes/accounting.index'
import { Route as TaxLaporanPajakRouteImport } from './routes/tax.laporan-pajak'
import { Route as FinanceDaftarTugasRouteImport } from './routes/finance.daftar-tugas'
import { Route as FinanceCashflowRouteImport } from './routes/finance.cashflow'
import { Route as DashboardSalesRouteImport } from './routes/dashboard.sales'
import { Route as DashboardProductionRouteImport } from './routes/dashboard.production'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard.inventory'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'
import { Route as AccountingProyeksiRouteImport } from './routes/accounting.proyeksi'
import { Route as AccountingLaporanRouteImport } from './routes/accounting.laporan'

const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxIndexRoute = TaxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaxRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountingIndexRoute = AccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountingRoute,
} as any)
const TaxLaporanPajakRoute = TaxLaporanPajakRouteImport.update({
  id: '/laporan-pajak',
  path: '/laporan-pajak',
  getParentRoute: () => TaxRoute,
} as any)
const FinanceDaftarTugasRoute = FinanceDaftarTugasRouteImport.update({
  id: '/daftar-tugas',
  path: '/daftar-tugas',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCashflowRoute = FinanceCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => FinanceRoute,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductionRoute = DashboardProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => DashboardRoute,
} as any)
const AccountingProyeksiRoute = AccountingProyeksiRouteImport.update({
  id: '/proyeksi',
  path: '/proyeksi',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingLaporanRoute = AccountingLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AccountingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/tax': typeof TaxRouteWithChildren
  '/accounting/laporan': typeof AccountingLaporanRoute
  '/accounting/proyeksi': typeof AccountingProyeksiRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/production': typeof DashboardProductionRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/finance/cashflow': typeof FinanceCashflowRoute
  '/finance/daftar-tugas': typeof FinanceDaftarTugasRoute
  '/tax/laporan-pajak': typeof TaxLaporanPajakRoute
  '/accounting/': typeof AccountingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/tax/': typeof TaxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounting/laporan': typeof AccountingLaporanRoute
  '/accounting/proyeksi': typeof AccountingProyeksiRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/production': typeof DashboardProductionRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/finance/cashflow': typeof FinanceCashflowRoute
  '/finance/daftar-tugas': typeof FinanceDaftarTugasRoute
  '/tax/laporan-pajak': typeof TaxLaporanPajakRoute
  '/accounting': typeof AccountingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/tax': typeof TaxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/finance': typeof FinanceRouteWithChildren
  '/login': typeof LoginRoute
  '/tax': typeof TaxRouteWithChildren
  '/accounting/laporan': typeof AccountingLaporanRoute
  '/accounting/proyeksi': typeof AccountingProyeksiRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/production': typeof DashboardProductionRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/finance/cashflow': typeof FinanceCashflowRoute
  '/finance/daftar-tugas': typeof FinanceDaftarTugasRoute
  '/tax/laporan-pajak': typeof TaxLaporanPajakRoute
  '/accounting/': typeof AccountingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/tax/': typeof TaxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting'
    | '/dashboard'
    | '/finance'
    | '/login'
    | '/tax'
    | '/accounting/laporan'
    | '/accounting/proyeksi'
    | '/dashboard/customer'
    | '/dashboard/inventory'
    | '/dashboard/production'
    | '/dashboard/sales'
    | '/finance/cashflow'
    | '/finance/daftar-tugas'
    | '/tax/laporan-pajak'
    | '/accounting/'
    | '/dashboard/'
    | '/finance/'
    | '/tax/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounting/laporan'
    | '/accounting/proyeksi'
    | '/dashboard/customer'
    | '/dashboard/inventory'
    | '/dashboard/production'
    | '/dashboard/sales'
    | '/finance/cashflow'
    | '/finance/daftar-tugas'
    | '/tax/laporan-pajak'
    | '/accounting'
    | '/dashboard'
    | '/finance'
    | '/tax'
  id:
    | '__root__'
    | '/'
    | '/accounting'
    | '/dashboard'
    | '/finance'
    | '/login'
    | '/tax'
    | '/accounting/laporan'
    | '/accounting/proyeksi'
    | '/dashboard/customer'
    | '/dashboard/inventory'
    | '/dashboard/production'
    | '/dashboard/sales'
    | '/finance/cashflow'
    | '/finance/daftar-tugas'
    | '/tax/laporan-pajak'
    | '/accounting/'
    | '/dashboard/'
    | '/finance/'
    | '/tax/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingRoute: typeof AccountingRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  FinanceRoute: typeof FinanceRouteWithChildren
  LoginRoute: typeof LoginRoute
  TaxRoute: typeof TaxRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax/': {
      id: '/tax/'
      path: '/'
      fullPath: '/tax/'
      preLoaderRoute: typeof TaxIndexRouteImport
      parentRoute: typeof TaxRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/accounting/': {
      id: '/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AccountingIndexRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/tax/laporan-pajak': {
      id: '/tax/laporan-pajak'
      path: '/laporan-pajak'
      fullPath: '/tax/laporan-pajak'
      preLoaderRoute: typeof TaxLaporanPajakRouteImport
      parentRoute: typeof TaxRoute
    }
    '/finance/daftar-tugas': {
      id: '/finance/daftar-tugas'
      path: '/daftar-tugas'
      fullPath: '/finance/daftar-tugas'
      preLoaderRoute: typeof FinanceDaftarTugasRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/cashflow': {
      id: '/finance/cashflow'
      path: '/cashflow'
      fullPath: '/finance/cashflow'
      preLoaderRoute: typeof FinanceCashflowRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/production': {
      id: '/dashboard/production'
      path: '/production'
      fullPath: '/dashboard/production'
      preLoaderRoute: typeof DashboardProductionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/accounting/proyeksi': {
      id: '/accounting/proyeksi'
      path: '/proyeksi'
      fullPath: '/accounting/proyeksi'
      preLoaderRoute: typeof AccountingProyeksiRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/laporan': {
      id: '/accounting/laporan'
      path: '/laporan'
      fullPath: '/accounting/laporan'
      preLoaderRoute: typeof AccountingLaporanRouteImport
      parentRoute: typeof AccountingRoute
    }
  }
}

interface AccountingRouteChildren {
  AccountingLaporanRoute: typeof AccountingLaporanRoute
  AccountingProyeksiRoute: typeof AccountingProyeksiRoute
  AccountingIndexRoute: typeof AccountingIndexRoute
}

const AccountingRouteChildren: AccountingRouteChildren = {
  AccountingLaporanRoute: AccountingLaporanRoute,
  AccountingProyeksiRoute: AccountingProyeksiRoute,
  AccountingIndexRoute: AccountingIndexRoute,
}

const AccountingRouteWithChildren = AccountingRoute._addFileChildren(
  AccountingRouteChildren,
)

interface DashboardRouteChildren {
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardProductionRoute: typeof DashboardProductionRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardProductionRoute: DashboardProductionRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface FinanceRouteChildren {
  FinanceCashflowRoute: typeof FinanceCashflowRoute
  FinanceDaftarTugasRoute: typeof FinanceDaftarTugasRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceCashflowRoute: FinanceCashflowRoute,
  FinanceDaftarTugasRoute: FinanceDaftarTugasRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface TaxRouteChildren {
  TaxLaporanPajakRoute: typeof TaxLaporanPajakRoute
  TaxIndexRoute: typeof TaxIndexRoute
}

const TaxRouteChildren: TaxRouteChildren = {
  TaxLaporanPajakRoute: TaxLaporanPajakRoute,
  TaxIndexRoute: TaxIndexRoute,
}

const TaxRouteWithChildren = TaxRoute._addFileChildren(TaxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingRoute: AccountingRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  FinanceRoute: FinanceRouteWithChildren,
  LoginRoute: LoginRoute,
  TaxRoute: TaxRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
